<?php

namespace AppBundle\Repository;

/**
 * invoiceDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invoiceDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
