<?php

namespace AppBundle\Repository;

/**
 * invoice_iteamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invoice_iteamsRepository extends \Doctrine\ORM\EntityRepository
{
}
